<?php
/* @var $this Edrone_Base_Block_Cart */
$helper = $this->getConfigHelper();
$helper2 = Mage::helper('edrone');
$customerData = $this->getCustomerData();
$productData = $this->getProductData();
?>

<?php if(!empty($productData)): ?>
    <script type="text/javascript">
        (function (srcjs) {
            window._edrone = window._edrone || {};
            _edrone.app_id = '<?php echo $helper->getAppId() ?>';
            _edrone.version = '1.1.16';
            _edrone.platform = 'Magento';
            _edrone.platform_version = '<?php echo Mage::getVersion(); ?>';
            _edrone.trace_url = '<?php echo $helper->getCollectorUrl() ?>';
            _edrone.is_logged_in = '<?php echo $customerData['is_logged_in'] ?>';
            _edrone.email = '<?php echo $customerData['email'] ?>';
            _edrone.phone = '<?php echo $customerData['phone'] ?>';
            _edrone.first_name = '<?php echo urlencode($customerData['first_name']); ?>';
            _edrone.last_name = '<?php echo urlencode($customerData['last_name']); ?>';
            _edrone.product_skus = '<?php echo $productData['sku'] ?>';
            _edrone.product_ids = '';
            _edrone.product_titles = '<?php echo urlencode($productData['title']); ?>';
            _edrone.product_images = '<?php echo urlencode($productData['image']); ?>';
            _edrone.product_category_ids = '<?php echo $productData['product_category_ids'] ?>';
            _edrone.product_category_names = '<?php echo urlencode($productData['product_category_names']); ?>';
            _edrone.order_id = '';
            _edrone.order_payment_value = '';
            _edrone.currency = '';
            _edrone.action_type = 'add_to_cart';
            _edrone.country = '<?php echo $customerData['country'] ?>';
            _edrone.city = '<?php echo urlencode($customerData['city']); ?>';
            _edrone.subscriber_status = '<?php echo $customerData['subscriber_status'] ?>';
            _edrone.utc_time = '<?php echo $helper2->utcNow() ?>';
            

            var doc = document.createElement('script');
            doc.type = 'text/javascript';
            doc.async = true;
            doc.src = ('https:' == document.location.protocol ? 'https:' : 'http:') + srcjs;
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(doc, s);

        })("<?php echo $helper->getExternalScriptUrl() ?>");
    </script>
<?php else: ?>
    <script type="text/javascript">
        (function (srcjs) {
            window._edrone = window._edrone || {};
            _edrone.app_id = '<?php echo $helper->getAppId() ?>';
            _edrone.version = '1.1.16';
            _edrone.platform = 'Magento';
            _edrone.platform_version = '<?php echo Mage::getVersion(); ?>';
            _edrone.trace_url = '<?php echo $helper->getCollectorUrl() ?>';
            _edrone.is_logged_in = '<?php echo $customerData['is_logged_in'] ?>';
            _edrone.email = '<?php echo $customerData['email'] ?>';
            _edrone.phone = '<?php echo $customerData['phone'] ?>';
            _edrone.first_name = '<?php echo urlencode($customerData['first_name']); ?>';
            _edrone.last_name = '<?php echo urlencode($customerData['last_name']); ?>';
            _edrone.product_skus = '';
            _edrone.product_ids = '';
            _edrone.product_titles = '';
            _edrone.product_images = '';
            _edrone.product_category_ids = '';
            _edrone.product_category_names = '';
            _edrone.order_id = '';
            _edrone.order_payment_value = '';
            _edrone.currency = '';
            _edrone.action_type = 'other';
            _edrone.country = '<?php echo $customerData['country'] ?>';
            _edrone.city = '<?php echo urlencode($customerData['city']); ?>';
            _edrone.subscriber_status = '<?php echo $customerData['subscriber_status'] ?>';
            _edrone.utc_time = '<?php echo $helper2->utcNow() ?>';
            

            var doc = document.createElement('script');
            doc.type = 'text/javascript';
            doc.async = true;
            doc.src = ('https:' == document.location.protocol ? 'https:' : 'http:') + srcjs;
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(doc, s);

        })("<?php echo $helper->getExternalScriptUrl() ?>");
    </script>
<?php endif; ?>