<?php
/* @var $this Edrone_Base_Block_Cart */
$helper = $this->getConfigHelper();
$customerData = $this->getCustomerData();
$productData = $this->getProductData();
?>

<?php if(!empty($productData)): ?>
    <script type="text/javascript">
        (function (srcjs) {
            window._edrone = window._edrone || {};
            _edrone.app_id = '<?php echo $helper->getAppId() ?>';
            _edrone.version = '1.0.3';
            _edrone.platform_version = '<?php echo Mage::getVersion(); ?>';
            _edrone.trace_url = '<?php echo $helper->getCollectorUrl() ?>';
            _edrone.is_logged_in = '<?php echo $customerData['is_logged_in'] ?>';
            _edrone.email = '<?php echo $customerData['email'] ?>';
            _edrone.phone = '<?php echo $customerData['phone'] ?>';
            _edrone.first_name = '<?php echo $customerData['first_name'] ?>';
            _edrone.last_name = '<?php echo $customerData['last_name'] ?>';
            _edrone.product_ids = '<?php echo $productData['sku'] ?>';
            _edrone.product_titles = '<?php echo $productData['title'] ?>';
            _edrone.product_images = '<?php echo $productData['image'] ?>';
            _edrone.order_id = '';
            _edrone.order_payment_value = '';
            _edrone.currency = '';
            _edrone.action_type = 'add_to_cart';
            _edrone.country = '<?php echo $customerData['country'] ?>';
            _edrone.city = '<?php echo $customerData['city'] ?>';

            var doc = document.createElement('script');
            doc.type = 'text/javascript';
            doc.async = true;
            doc.src = ('https:' == document.location.protocol ? 'https:' : 'http:') + srcjs;
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(doc, s);

        })("<?php echo $helper->getExternalScriptUrl() ?>");
    </script>
<?php endif; ?>